---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-credentials
  namespace: tailscale
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tailscale-operator-credentials
    creationPolicy: Owner
  data:
    - secretKey: oauth_client_id
      remoteRef:
        key: Tailscale/oauth_client_id
    - secretKey: oauth_client_secret
      remoteRef:
        key: Tailscale/oauth_client_secret
