---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-secret
  namespace: arc-runners
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-app-secret
    creationPolicy: Owner
  data:
    # GitHub App credentials - create in 1Password as "GitHub ARC"
    - secretKey: github_app_id
      remoteRef:
        key: GitHub ARC/app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: GitHub ARC/installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: GitHub ARC/pid1co-arc-runners.2026-03-24.private-key.pem
