---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arc-build-cache
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 20Gi
