---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - clawshell-externalsecret.yaml
  - pushover-externalsecret.yaml
  - ghcr-credentials.yaml
  - openclaw-config.yaml
  - nginx-config.yaml
  - storage.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - vpa.yaml
