---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pushover-secrets
  namespace: openclaw-personal
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pushover-secrets
    creationPolicy: Owner
  data:
    - secretKey: user-key
      remoteRef:
        key: Pushover/user_key
    - secretKey: app-token
      remoteRef:
        key: Pushover/app_token
