---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fmp-mcp-secrets
  namespace: mcp-servers
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fmp-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: fmp-api-key
      remoteRef:
        key: FMP MCP Server/api_key
