---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-api-key
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: truenas-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: TrueNAS CSI Config/api_key
