---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-csi-config
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: truenas-csi-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config: |
          driver: freenas-api-nfs
          httpConnection:
            protocol: http
            host: "192.168.254.1"
            port: 80
            apiKey: "{{ .api_key }}"
            allowInsecure: true
          zfs:
            datasetParentName: "tank/homelab-k8s/volumes"
            detachedSnapshotsDatasetParentName: "tank/homelab-k8s/snapshots"
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0770"
            datasetPermissionsUser: 1000
            datasetPermissionsGroup: 1337
          nfs:
            shareHost: "192.168.254.1"
            shareAlldirs: false
            shareAllowedHosts:
              - "192.168.254.2"
            shareAllowedNetworks:
              - "192.168.254.0/30"
            shareMaprootUser: "root"
            shareMaprootGroup: "wheel"
  data:
    - secretKey: api_key
      remoteRef:
        key: TrueNAS CSI Config
        property: api_key
