---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-credentials
  namespace: observability
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: influxdb-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user-password
      remoteRef:
        key: InfluxDB
        property: admin_password
    - secretKey: admin-user-token
      remoteRef:
        key: InfluxDB
        property: admin_token
