---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: influxdb
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb-influxdb2.observability.svc:80
    isDefault: false
    jsonData:
      version: Flux
      organization: homelab
      defaultBucket: forex
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
  valuesFrom:
    - targetPath: "secureJsonData.token"
      valueFrom:
        secretKeyRef:
          name: influxdb-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-token
  namespace: observability
spec:
  refreshInterval: 4h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: influxdb-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: OpenClaw Trading
        property: influx_token
